apiVersion: v1
kind: Service
metadata:
  name: traceproducer-srv
spec:
  selector:
    app: traceproducer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceproducer-dpl
  labels:
    app: traceproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceproducer
  template:
    metadata:
      labels:
        app: traceproducer
    spec:
      containers:
      - name: traceproducer
        image: ghcr.io/yourGitHubUsername/traceproducer
        ports:
        - containerPort: 8080
        env:
        - name: spring.cloud.stream.kafka.binder.brokers
          value: "${KAFKA_SERVICE_SERVICE_HOST}:9092" # Configuración para Kafka
        - name: TRANSPORTATION_ORDER_SERVICE_HOST
          value: "transportation-order-service" # Configuración para TransportationOrderService
        - name: TRANSPORTATION_ORDER_SERVICE_PORT
          value: "8080" # Puerto del servicio TransportationOrderService
      imagePullSecrets:
      - name: github-registry