apiVersion: v1
kind: Service
metadata:
  name: traceserver-srv
spec:
  selector:
    app: traceserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceserver-dpl
  labels:
    app: traceserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceserver
  template:
    metadata:
      labels:
        app: traceserver
    spec:
      containers:
      - name: traceserver
        image: ghcr.io/sandracascantem/tr
        ports:
        - containerPort: 8080
        env:
        - name: spring.cloud.stream.kafka.binder.brokers
          value: "${KAFKA_SERVICE_SERVICE_HOST}:9092" # Configuración para Kafka
        - name: TRANSPORTATION_ORDER_SERVICE_HOST
          value: "transportation-order-service" # Configuración para TransportationOrderServer
        - name: TRANSPORTATION_ORDER_SERVICE_PORT
          value: "8080" # Puerto del servicio TransportationOrderServer
      imagePullSecrets:
      - name: github-registry