apiVersion: v1
kind: Service
metadata:
  name: transportationorderserver-srv
spec:
  selector:
    app: transportationorderserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: transportationorderserver-dpl
  labels:
    app: transportationorderserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transportationorderserver
  template:
    metadata:
      labels:
        app: transportationorderserver
    spec:
      containers:
      - name: transportationorderserver
        image: ghcr.io/sandracascantem/tos
        ports:
        - containerPort: 8080
      #
      env:
        - name: spring.cloud.stream.kafka.binder.brokers
          value: "${KAFKA_SERVICE_SERVICE_HOST}:9092"
      imagePullSecrets:
      - name: github-registry